export const citiesData: Record<string, any> = {
  riyadh: {
    name: 'Riyadh',
    title: 'Luxury Chauffeur Service Riyadh | Private Driver & VIP Airport Transfer',
    intro: `Riyadh, the majestic capital and largest city of Saudi Arabia, stands as a testament to the Kingdom's rapid evolution and deep-rooted heritage. As the country's primary financial hub and the seat of government, Riyadh is a bustling metropolis where business, diplomacy, and culture converge. Navigating this vast city requires a transportation partner who understands the value of time and the necessity of comfort. Our premium chauffeur services in Riyadh are meticulously designed to provide seamless transportation for high-level executives, VIP travelers, and discerning visitors. Whether you are heading to a critical board meeting in the King Abdullah Financial District (KAFD), attending an event at the Diplomatic Quarter, or exploring the historic ruins of Diriyah, our professional drivers ensure you arrive with poise and punctuality. We pride ourselves on offering a sanctuary of luxury amidst the city's dynamic pace, allowing you to focus on your professional objectives or simply soak in the city's unique skyline. Our local expertise means we navigate the most efficient routes, avoiding traffic bottlenecks and ensuring your schedule remains uninterrupted.`,
    metaDescription: 'Luxury chauffeur in Riyadh for business or leisure. Professional private drivers and premium transfers at King Khalid International (RUH).',
    airport: `King Khalid International Airport (RUH) serves as the primary international gateway to the capital. Recognizing that the airport experience can be demanding, we offer high-touch meet and greet services that begin the moment you land. Our dedicated chauffeurs monitor your flight in real-time, adjusting for any delays to ensure a prompt pickup. Upon arrival, you will be met with a personalized sign and assisted with your luggage through the terminal. We provide expedited transfers to all major districts in Riyadh, including the city center, which is approximately a 35 to 45-minute drive depending on traffic. Our fleet of high-end vehicles, ranging from the Mercedes S-Class to the spacious GMC Yukon XL, ensures that your journey from the terminal to your destination is as relaxing and productive as possible.`,
    popularRoutes: ['Riyadh to Jeddah', 'Riyadh to Dammam', 'Riyadh to Makkah'],
    fleet: ['Mercedes S-Class', 'BMW 7 Series', 'GMC Yukon XL'],
    faqs: [
      { q: 'How far is Riyadh Airport from the city center?', a: 'Riyadh Airport (RUH) is approximately 35km from the city center, taking around 30-45 minutes by chauffeur.' },
      { q: 'Can I book a chauffeur for a full day in Riyadh?', a: 'Yes, we offer flexible hourly and full-day chauffeur hire for business meetings and city sightseeing.' }
    ]
  },
  jeddah: {
    name: 'Jeddah',
    title: 'Luxury Chauffeur Service Jeddah | Private Driver & VIP Airport Transfer',
    intro: `Jeddah, often referred to as the "Bride of the Red Sea," is a vibrant coastal city that serves as the commercial heart of Saudi Arabia and the traditional gateway to the holy cities of Makkah and Madinah. Known for its eclectic blend of modern skyscrapers and the UNESCO World Heritage site of Al-Balad, Jeddah offers a unique experience for every traveler. Our premium chauffeur services in Jeddah are tailored to meet the diverse needs of business travelers, luxury tourists, and religious pilgrims. Whether you are in town for an international conference, a shopping spree at the Red Sea Mall, or simply to enjoy the breathtaking views along the Jeddah Corniche, our professional drivers provide a level of service that is both sophisticated and reliable. We understand the nuances of Jeddah's roads and the importance of arriving at your destination refreshed and ready. Our chauffeurs are not just drivers; they are local experts who can guide you through the city's cultural landmarks and hidden gems with ease and discretion.`,
    metaDescription: 'Premium chauffeur services in Jeddah. Luxury airport transfers from JED and private drivers for business, tourism, and Umrah pilgrims.',
    airport: `King Abdulaziz International Airport (JED) is one of the busiest and most modern aviation hubs in the Middle East, featuring the spectacular new Terminal 1 and the dedicated Hajj terminal. We specialize in luxury airport transfers that take the stress out of arrival and departure. Our meet and greet service ensures a smooth transition from the gate to your private vehicle. For pilgrims arriving for Umrah, we provide specialized transportation directly to Makkah, ensuring a comfortable start to their spiritual journey. The airport is conveniently located about 20km north of the city center, and our chauffeurs utilize the most efficient routes to ensure you reach your hotel or business meeting in record time. With our premium fleet, you can enjoy a quiet, climate-controlled environment while our drivers handle the navigation and traffic.`,
    popularRoutes: ['Jeddah to Makkah', 'Jeddah to Madinah', 'Jeddah to Riyadh'],
    fleet: ['Cadillac Escalade', 'Mercedes V-Class', 'Mercedes S-Class'],
    faqs: [
      { q: 'How long does it take from Jeddah to Makkah?', a: 'The journey typically takes about 1 hour and 15 minutes, depending on traffic and the specific terminal.' },
      { q: 'Do you offer airport transfers for pilgrims?', a: 'Yes, we specialize in luxury Umrah transfers from JED airport to hotels in Makkah.' }
    ]
  },
  makkah: {
    name: 'Makkah',
    title: 'Elite Chauffeur Service Makkah | Private Driver & Hajj/Umrah Transfer',
    intro: `Makkah is the holiest city in the Islamic world, attracting millions of faithful pilgrims every year for Hajj and Umrah. In a city of such profound spiritual significance, the importance of a dignified, reliable, and comfortable transportation service cannot be overstated. Our specialized chauffeur services in Makkah are designed to provide spiritual pilgrims and distinguished visitors with a sanctuary of peace during their stay. Navigating the dense crowds and complex traffic patterns around the Grand Mosque (Al-Masjid al-Haram) requires local expertise and patience. Our professional drivers are well-versed in the city's geography and are dedicated to ensuring that your movements between your hotel and the holy sites are as seamless as possible. We offer 24/7 private driver services, allowing you to focus entirely on your spiritual reflections while we manage the logistical details of your journey. From the towering Abraj Al Bait to the serene surroundings of Jabal al-Nour, our service provides the comfort and privacy that a journey of this importance deserves.`,
    metaDescription: 'Chauffeur services in Makkah for Umrah and Hajj. Luxury private transfers from Jeddah airport and premium local driver services 24/7.',
    airport: `While Makkah does not have its own airport, most visitors arrive via the King Abdulaziz International Airport in Jeddah or the airport in Madinah. We provide seamless, high-end intercity transfers to ensure your arrival in Makkah is smooth and stress-free. Our chauffeurs will meet you at the airport and drive you directly to your hotel in Makkah, handling all luggage and route planning. We understand the specific requirements of pilgrims and offer vehicles that can accommodate families and groups, such as the GMC Yukon XL and Mercedes V-Class. Our commitment to excellence ensures that the final leg of your journey to the Holy City is handled with the utmost care and professionalism, providing a comfortable environment for rest and preparation.`,
    popularRoutes: ['Makkah to Madinah', 'Makkah to Jeddah', 'Makkah to Riyadh'],
    fleet: ['GMC Yukon XL', 'Mercedes V-Class', 'BMW 7 Series'],
    faqs: [
      { q: 'Can your chauffeurs access all areas in Makkah?', a: 'Yes, our local chauffeurs are fully authorized and experienced in navigating Makkah for guest drops near the Haram.' },
      { q: 'Is it possible to book a round trip between Makkah and Madinah?', a: 'Absolutely, we offer seamless round-trip intercity transfers between the two holy cities.' }
    ]
  },
  madinah: {
    name: 'Madinah',
    title: 'Premium Chauffeur Service Madinah | Private Driver & Ziyarat Tours',
    intro: `Madinah Al-Munawwarah, the "Radiant City," holds a special place in the hearts of Muslims as the home of the Prophet’s Mosque (Al-Masjid an-Nabawi). It is a city characterized by its serene atmosphere and historical depth. For visitors and pilgrims seeking a peaceful and respectful journey, our premium chauffeur services in Madinah offer the perfect solution. We understand that time spent in Madinah is precious, and our goal is to enhance your experience by providing reliable, high-quality transportation. Whether you are visiting the historic Quba Mosque, the Mount of Uhud, or the Baqi cemetery, our professional drivers ensure a comfortable and dignified transit. Our fleet of luxury sedans and spacious SUVs provides a tranquil space where you can prepare for your prayers or reflect on your visit. We pride ourselves on our punctuality and our ability to navigate the city’s streets with discretion and care, ensuring that your spiritual journey remains uninterrupted by logistical concerns.`,
    metaDescription: 'Premium chauffeur and private driver services in Madinah. Luxury transfers from MED airport and transport for Prophet’s Mosque visits.',
    airport: `Prince Mohammad Bin Abdulaziz International Airport (MED) serves as the primary gateway for those visiting the Prophet’s city. Our luxury meet and greet services at MED are designed to provide an immediate sense of hospitality and ease upon your arrival. Our chauffeurs monitor your flight status to ensure they are waiting for you at the terminal, ready to assist with your luggage and guide you to your waiting vehicle. The airport is located approximately 15km from the Prophet's Mosque, and our drivers are experts at navigating the most efficient routes to ensure you reach your accommodation quickly. Whether you are arriving internationally or domestically, our service provides a seamless transition from the airport to the heart of Madinah, allowing you to begin your visit in total comfort.`,
    popularRoutes: ['Madinah to Makkah', 'Madinah to Jeddah', 'Madinah to AlUla'],
    fleet: ['Mercedes S-Class', 'Chevrolet Suburban', 'BMW 7 Series'],
    faqs: [
      { q: 'Do you provide transfers to the Prophet’s Mosque?', a: 'Yes, our chauffeurs can drop you off at the closest possible points to the mosque entrances.' },
      { q: 'Can I book a tour of Ziyarat sites in Madinah?', a: 'Yes, we offer half-day and full-day chauffeur services for visiting historical sites in Madinah.' }
    ]
  },
  dammam: {
    name: 'Dammam',
    title: 'Executive Chauffeur Service Dammam | Private Driver & Airport Transfer',
    intro: `Dammam, together with the neighboring cities of Khobar and Dhahran, forms the bustling Dammam Metropolitan Area, the industrial and commercial heartbeat of Saudi Arabia's Eastern Province. As the headquarters for global energy giants like Saudi Aramco, this region is a critical destination for international business leaders and technical experts. Our executive chauffeur services in Dammam are specifically tailored to meet the high standards of the corporate world. We provide reliable, high-stakes transportation that ensures you arrive at your meetings, project sites, or corporate events on time and in a state of professional readiness. Beyond business, the Eastern Province offers beautiful coastal vistas along the Khobar Corniche and cultural landmarks like the Ithra Center. Our professional drivers possess an intimate knowledge of the region's road networks, including the King Fahd Causeway to Bahrain, ensuring that your travel within and beyond the province is handled with maximum efficiency and comfort.`,
    metaDescription: 'Executive chauffeur services in Dammam, Khobar, and Dhahran. Professional private drivers for corporate travel and DMM airport transfers.',
    airport: `King Fahd International Airport (DMM) is renowned as the largest airport by land area in the world. Navigating such a vast facility can be daunting, which is why our specialized airport transfer services are essential for the savvy traveler. We offer a comprehensive meet and greet service that streamlines your arrival, with a professional chauffeur waiting to assist you from the moment you exit the arrivals hall. We provide direct transfers to all major business hubs in Dammam, Khobar, and Dhahran, as well as industrial areas like Jubail. Additionally, we offer luxury cross-border chauffeur services for those traveling to Manama, Bahrain. Our fleet of executive vehicles provides a mobile office environment where you can stay connected and productive while our drivers manage the journey across the Eastern Province.`,
    popularRoutes: ['Dammam to Riyadh', 'Dammam to Khobar', 'Dammam to Manama'],
    fleet: ['BMW 7 Series', 'Cadillac Escalade', 'Mercedes S-Class'],
    faqs: [
      { q: 'Do you offer transfers to Bahrain from Dammam?', a: 'Yes, we provide luxury cross-border chauffeur services from Dammam and Khobar to Manama via the King Fahd Causeway.' },
      { q: 'Is chauffeur service available in Dhahran?', a: 'We serve all major areas in the Eastern Province, including Dammam, Khobar, Dhahran, and Jubail.' }
    ]
  }
};
